In [1]:
import numpy as np
import pickle
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding,LSTM,Dense


In [5]:
with open('/content/IndiaUS.txt','r',encoding='utf-8') as myfile:
  mytext=myfile.read()

In [6]:
print(mytext)

Following a lavish state visit by Indian Prime Minister Narendra Modi to Washington, US President Joe Biden has called his country's partnership with India among the "most consequential in the world". The BBC's Vikas Pandey and Soutik Biswas explore the factors that contribute to the visit's potential in strengthening the ties between the two nations.

The US's relationship with India - the world's most populous country - is "stronger, closer and more dynamic than any time in history", Mr Biden said at the completion of a pomp-filled state visit by Mr Modi to the White House.

The remark may not be an exaggeration. "This summit suggests that the relationship has been transformed. It underscores just how broad and deep it has become in a relatively short time," says Michael Kugelman of The Wilson Center, an American think-tank.

A key reason is that Washington is keen to draw India closer so that it can act as a counterbalance to China's growing influence in the Indo-Pacific. India-US t

In [7]:
mytokenizer=Tokenizer()

In [8]:
mytokenizer.fit_on_texts([mytext])

In [9]:
total_words=len(mytokenizer.word_index)+1 # space for extra word out of vocabulary token
total_words

599

In [10]:
mytokenizer.word_index

{'the': 1,
 'to': 2,
 'in': 3,
 'a': 4,
 'and': 5,
 'india': 6,
 'of': 7,
 'mr': 8,
 'us': 9,
 'is': 10,
 'modi': 11,
 'has': 12,
 'that': 13,
 'biden': 14,
 'as': 15,
 'with': 16,
 'not': 17,
 "india's": 18,
 'for': 19,
 'but': 20,
 'on': 21,
 'washington': 22,
 'an': 23,
 'it': 24,
 'says': 25,
 'will': 26,
 'are': 27,
 'indian': 28,
 'prime': 29,
 'minister': 30,
 'this': 31,
 'have': 32,
 'trade': 33,
 'visit': 34,
 'by': 35,
 'president': 36,
 'relationship': 37,
 'been': 38,
 'about': 39,
 'strategic': 40,
 'more': 41,
 'up': 42,
 'during': 43,
 'also': 44,
 'make': 45,
 'sirohi': 46,
 'china': 47,
 'air': 48,
 'force': 49,
 'state': 50,
 'his': 51,
 'ties': 52,
 'two': 53,
 'at': 54,
 'white': 55,
 'house': 56,
 'be': 57,
 'lot': 58,
 'ms': 59,
 'technology': 60,
 'jet': 61,
 'semiconductor': 62,
 'now': 63,
 'first': 64,
 'was': 65,
 'global': 66,
 'one': 67,
 'he': 68,
 'without': 69,
 'they': 70,
 'narendra': 71,
 'joe': 72,
 'world': 73,
 'potential': 74,
 'how': 75,
 'becom

In [11]:
with open('tokenizer.pickle','wb') as handle:
  pickle.dump(mytokenizer,handle,protocol=pickle.HIGHEST_PROTOCOL)

In [12]:
my_input_sequences=[]
for line in mytext.split('\n'):
  token_list=mytokenizer.texts_to_sequences([line])[0]

  print(token_list)


  for i in range(1,len(token_list)):
    #n gram sequences
    my_ngram_sequence=token_list[:i+1]
    my_input_sequences.append(my_ngram_sequence)

[99, 4, 177, 50, 34, 35, 28, 29, 30, 71, 11, 2, 22, 9, 36, 72, 14, 12, 178, 51, 100, 101, 16, 6, 179, 1, 102, 180, 3, 1, 73, 1, 181, 182, 183, 5, 184, 185, 186, 1, 187, 13, 188, 2, 1, 189, 74, 3, 103, 1, 52, 104, 1, 53, 105]
[]
[1, 190, 37, 16, 6, 1, 191, 102, 192, 193, 10, 194, 106, 5, 41, 195, 107, 196, 108, 3, 197, 8, 14, 109, 54, 1, 198, 7, 4, 199, 200, 50, 34, 35, 8, 11, 2, 1, 55, 56]
[]
[1, 201, 110, 17, 57, 23, 202, 31, 203, 204, 13, 1, 37, 12, 38, 205, 24, 206, 207, 75, 111, 5, 208, 24, 12, 76, 3, 4, 209, 210, 108, 25, 211, 77, 7, 1, 212, 213, 23, 214, 215, 216]
[]
[4, 217, 112, 10, 13, 22, 10, 218, 2, 219, 6, 106, 220, 13, 24, 113, 221, 15, 4, 222, 2, 114, 223, 224, 3, 1, 115, 116, 6, 9, 52, 117, 17, 225, 42, 2, 226, 227, 99, 4, 228, 229, 230, 231, 3, 232, 118, 4, 233, 234, 235, 35, 6, 236, 78, 119, 237, 120, 7, 238]
[]
[31, 239, 4, 240, 241, 2, 1, 37, 43, 121, 29, 30, 242, 243, 244, 245, 15, 1, 246, 7, 4, 247, 248, 16, 8, 11, 79, 12, 38, 4, 58, 41, 249, 39, 250, 1, 9, 8, 14, 

In [13]:
max_sequence_len=max([len(seq) for seq in my_input_sequences])
max_sequence_len

83

In [14]:
input_sequence=np.array(pad_sequences(my_input_sequences,maxlen=max_sequence_len,padding='pre'))
input_sequence



array([[  0,   0,   0, ...,   0,  99,   4],
       [  0,   0,   0, ...,  99,   4, 177],
       [  0,   0,   0, ...,   4, 177,  50],
       ...,
       [  0,   0,   0, ..., 176, 598,  25],
       [  0,   0,   0, ..., 598,  25,  59],
       [  0,   0,   0, ...,  25,  59,  46]], dtype=int32)

In [17]:
x=input_sequence[:,:-1]
y=input_sequence[:,-1]

In [18]:
x

array([[  0,   0,   0, ...,   0,   0,  99],
       [  0,   0,   0, ...,   0,  99,   4],
       [  0,   0,   0, ...,  99,   4, 177],
       ...,
       [  0,   0,   0, ...,   5, 176, 598],
       [  0,   0,   0, ..., 176, 598,  25],
       [  0,   0,   0, ..., 598,  25,  59]], dtype=int32)

In [19]:
y

array([  4, 177,  50, ...,  25,  59,  46], dtype=int32)

In [20]:
y=np.array(tf.keras.utils.to_categorical(y,num_classes=total_words))
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [21]:
from keras.models import Sequential
model=Sequential()
model.add(Embedding(input_dim=total_words,output_dim=100,input_length=max_sequence_len-1))

model.add(LSTM(150))
model.add(Dense(total_words,activation='softmax'))


In [22]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])


In [36]:
model.fit(x,y,epochs=500,verbose=1)

Epoch 1/500
43/43 [==============================] - 5s 81ms/step - loss: 0.0259 - accuracy: 0.9876
Epoch 2/500
43/43 [==============================] - 3s 74ms/step - loss: 0.0260 - accuracy: 0.9869
Epoch 3/500
43/43 [==============================] - 2s 47ms/step - loss: 0.0265 - accuracy: 0.9861
Epoch 4/500
43/43 [==============================] - 2s 41ms/step - loss: 0.0263 - accuracy: 0.9861
Epoch 5/500
43/43 [==============================] - 2s 36ms/step - loss: 0.0260 - accuracy: 0.9869
Epoch 6/500
43/43 [==============================] - 1s 21ms/step - loss: 0.0256 - accuracy: 0.9869
Epoch 7/500
43/43 [==============================] - 1s 28ms/step - loss: 0.0262 - accuracy: 0.9861
Epoch 8/500
43/43 [==============================] - 1s 17ms/step - loss: 0.0263 - accuracy: 0.9854
Epoch 9/500
43/43 [==============================] - 1s 15ms/step - loss: 0.0260 - accuracy: 0.9861
Epoch 10/500
43/43 [==============================] - 1s 24ms/step - loss: 0.0260 - accuracy: 0.9861

In [38]:
model.save('word_prediction2.h5')

In [27]:
!cp /content/tokenizer.pickle /content/drive/MyDrive/rnn

cp: cannot create regular file '/content/drive/MyDrive/rnn': No such file or directory


In [26]:
!cp /content/drive/MyDrive/tokenizer.pickle /content/drive/MyDrive/rnn

cp: cannot stat '/content/drive/MyDrive/tokenizer.pickle': No such file or directory


In [39]:
import numpy as np
import tensorflow as tf
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import pickle


In [40]:
with open('/content/tokenizer.pickle','rb') as handle:
  mytokenizer=pickle.load(handle)
model=tf.keras.models.load_model('/content/word_prediction2.h5')

In [49]:
input_text= 'semiconductor'
predict_next_words=15
for i in range(predict_next_words):
  token_list=mytokenizer.texts_to_sequences([input_text])[0]
  token_list=pad_sequences([token_list],maxlen=model.input_shape[1],padding='pre')

  predicted1=(model.predict(token_list))
  predicted1_index=np.argmax(predicted1,axis=1)
  output_word=mytokenizer.index_word[predicted1_index[0]]
  input_text+=" "+output_word
print(input_text)

1/1 [==============================] - 0s 17ms/step
semiconductor key reason is that washington is keen to draw india closer so that it can


In [50]:
predicted1

array([[1.51955466e-12, 3.97771930e-13, 1.47154433e-09, 1.78889394e-14,
        1.23353966e-10, 4.13023532e-10, 6.74132982e-15, 2.16463024e-12,
        8.56607198e-14, 1.39705261e-11, 4.84217026e-07, 1.97087979e-13,
        4.65144069e-11, 3.26877969e-11, 2.28763321e-14, 5.32680176e-08,
        1.37065387e-10, 3.81642368e-16, 2.75501998e-15, 3.38331902e-12,
        9.37268510e-07, 1.77345950e-11, 3.02499237e-13, 2.29615593e-19,
        7.99943905e-07, 7.19355131e-12, 3.32931213e-14, 3.75243050e-15,
        1.53476798e-16, 1.13123167e-15, 3.77741848e-12, 6.72221474e-14,
        2.87645907e-10, 1.23272538e-11, 2.46279857e-13, 8.23674489e-15,
        4.18680322e-14, 8.93950780e-14, 5.21756978e-11, 1.14320931e-11,
        1.03733599e-08, 3.88595846e-14, 1.32932128e-08, 1.67802594e-09,
        5.98297995e-14, 1.53628975e-14, 4.24322816e-12, 1.16146426e-08,
        5.82468082e-16, 1.72947675e-13, 7.21137594e-10, 1.22429075e-17,
        2.98246289e-11, 3.33364878e-16, 3.27197880e-15, 7.187255

In [51]:
input_text= 'india'
predict_next_words=15
for i in range(predict_next_words):
  token_list=mytokenizer.texts_to_sequences([input_text])[0]
  token_list=pad_sequences([token_list],maxlen=model.input_shape[1],padding='pre')

  predicted2=(model.predict(token_list))
  predicted2_index=np.argmax(predicted2,axis=1)
  output_word=mytokenizer.index_word[predicted2_index[0]]
  input_text+=" "+output_word
print(input_text)

1/1 [==============================] - 0s 27ms/step
india and the us have had major trade differences in recent years over tariffs trade relations


In [52]:
predicted2

array([[7.47755590e-13, 2.41301628e-08, 3.14529392e-12, 6.75735455e-13,
        4.37696008e-14, 1.34836716e-11, 5.98820646e-12, 1.29340511e-10,
        6.54252650e-12, 8.30034208e-10, 2.28612092e-14, 4.55685296e-17,
        9.69033014e-12, 8.24955160e-10, 1.59948487e-12, 2.67261644e-08,
        3.60276226e-16, 4.88106666e-09, 4.17160837e-12, 1.87736965e-13,
        1.51661503e-10, 6.66312776e-14, 7.11040818e-13, 8.62575961e-13,
        3.82001453e-09, 1.86400645e-14, 2.37634547e-11, 4.07841732e-16,
        5.29966661e-11, 1.10523971e-12, 8.73645081e-16, 2.56152098e-14,
        4.51117789e-12, 1.41081262e-06, 1.74530518e-12, 7.41023555e-15,
        1.07725020e-13, 1.31609013e-07, 5.72925431e-12, 3.82741460e-14,
        1.52881494e-08, 3.50736717e-10, 1.56415188e-14, 4.42028920e-08,
        9.45281722e-14, 8.90250262e-14, 3.74272477e-15, 6.95502544e-10,
        8.30893427e-12, 6.22466488e-14, 8.35254623e-17, 9.12055347e-15,
        7.16646653e-08, 1.01343218e-12, 3.49209897e-11, 1.895493